### ISSUE TITLE
Memory allocation failures during publish

### ISSUE THREAD

**Issue by xraj** [smira/aptly#338]
Attempting to publish a snapshot of a wheezy mirror results in panics due to memory allocation failures while publishing a snapshot. After running the publish command dists/wheezy is empty.

The machine is an EC2 instance with 1GiB of RAM assigned. I'm not sure what kind of memory utilization is considered reasonable.

I'm running the latest snapshot from APT.

```
$ dpkg-query -s aptly | grep Version
Version: 0.9.6~dev+156+g339bf0a
```

Steps to reproduce.

```
aptly mirror create wheezy-main http://cloudfront.debian.net/debian wheezy main
aptly mirror update wheezy-main
aptly snapshot create wheezy-main-20160126-1 from mirror wheezy-main
aptly publish snapshot wheezy-main-20160126-1
```

Panic output.

```
panic: unable to unxz data.tar.xz from /srv/apt/pool/07/a1/kde-icons-mono_4.8.4-5_all.deb: fork/exec /usr/bin/xz: cannot allocate memory [recovered]
	panic: unable to unxz data.tar.xz from /srv/apt/pool/07/a1/kde-icons-mono_4.8.4-5_all.deb: fork/exec /usr/bin/xz: cannot allocate memory

goroutine 1 [running]:
github.com/smira/aptly/cmd.Run.func1(0xc826fa3f18)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/cmd/run.go:16 +0x7f
github.com/smira/aptly/deb.(*Package).CalculateContents(0xc821773440, 0x7f10793c4ea0, 0xc820e03840, 0x0, 0x0, 0x0)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/package.go:433 +0x1b4
github.com/smira/aptly/deb.(*PackageCollection).loadContents(0xc820e03940, 0xc821773440, 0x7f10793c4ea0, 0xc820e03840, 0x0, 0x0, 0x0)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/package_collection.go:183 +0x37b
github.com/smira/aptly/deb.(*Package).Contents(0xc821773440, 0x7f10793c4ea0, 0xc820e03840, 0x0, 0x0, 0x0)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/package.go:413 +0xfa
github.com/smira/aptly/deb.(*ContentsIndex).Push(0xc8230b44a0, 0xc821773440, 0x7f10793c4ea0, 0xc820e03840)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/contents.go:26 +0x4a
github.com/smira/aptly/deb.(*PublishedRepo).Publish.func1(0xc821773440, 0x0, 0x0)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/publish.go:567 +0x8d5
github.com/smira/aptly/deb.(*PackageList).ForEachIndexed(0xc820dfee70, 0xc826fa3508, 0x0, 0x0)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/list.go:139 +0xed
github.com/smira/aptly/deb.(*PublishedRepo).Publish(0xc820165d40, 0x7f10793c4ea0, 0xc820e03840, 0x7f10793c4f58, 0xc8200d3810, 0xc82000a1c0, 0x7f10793c4e48, 0xc82001dda0, 0x7f10793c4ee8, 0xc820dff0b0, ...)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/publish.go:592 +0x1135
github.com/smira/aptly/cmd.aptlyPublishSnapshotOrRepo(0xc8201605a0, 0xc82015db20, 0x1, 0x2, 0x0, 0x0)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/cmd/publish_snapshot.go:143 +0x14cb
github.com/smira/commander.(*Command).Dispatch(0xc8201605a0, 0xc82015db20, 0x1, 0x2, 0x0, 0x0)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:305 +0x647
github.com/smira/commander.(*Command).Dispatch(0xc820160900, 0xc82015db10, 0x2, 0x3, 0x0, 0x0)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:283 +0x1f0
github.com/smira/commander.(*Command).Dispatch(0xc8201610e0, 0xc82015db00, 0x3, 0x4, 0x0, 0x0)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:283 +0x1f0
github.com/smira/aptly/cmd.Run(0xc8201610e0, 0xc82000a190, 0x3, 0x3, 0xc3ec01, 0x0)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/cmd/run.go:40 +0x19a
main.main()
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/main.go:9 +0x73

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/home/smira/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 6 [syscall, 1 minutes]:
os/signal.loop()
	/home/smira/.gvm/gos/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/home/smira/.gvm/gos/go1.5/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [runnable]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc82014a1c0)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x29d
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x26b

goroutine 22 [sleep]:
time.Sleep(0xbebc200)
	/home/smira/.gvm/gos/go1.5/src/runtime/time.go:59 +0xf9
github.com/cheggaaa/pb.(*ProgressBar).writer(0xc822f82a50)
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/cheggaaa/pb/pb.go:332 +0x5b
created by github.com/cheggaaa/pb.(*ProgressBar).Start
	/home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/cheggaaa/pb/pb.go:101 +0x9c
```

**Comment by xraj** [comment]
I notice this problem is referenced in issue as well #297.

**Comment by xraj** [comment]
Swung the pendulum all the way to the other side, and tried this again on a t2.large instance with 8 gigs of RAM. Also just noticed that there was no swap enabled on the other machine.

Seems to be happy now. The unbound memory consumption seems to be entirely from unxz processes. aptly itself seems to consistently have a virtual size of 600M.

**Comment by smira** [comment]
So this might be related to `Contents` file generation. (that's what is using unxz)

**Comment by smira** [comment]
#347 might help here (disabling contents generation in config)

**Comment by david-gregory-inmar** [comment]
I think this may be related?  Was doing "aptly publish switch" to an S3 repo:

```
Loading packages...
Generating metadata files and linking package files...
Finalizing metadata files...
Cleaning up prefix "." components main...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x756622]

goroutine 1 [running]:
github.com/smira/aptly/cmd.Run.func1(0xc82c0f1f08)
        /Users/smira/Documents/go/src/github.com/smira/aptly/cmd/run.go:16 +0x7f
github.com/smira/aptly/s3.(*PublishedStorage).internalFilelist(0xc820615180, 0xc8234e32a0, 0x14, 0xc821469801, 0xc823aee000, 0x35a, 0x400, 0xc823c1c000, 0x35a, 0x400, ...)
        /Users/smira/Documents/go/src/github.com/smira/aptly/s3/public.go:305 +0x7f2
github.com/smira/aptly/s3.(*PublishedStorage).Filelist(0xc820615180, 0xc822cd6b70, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/smira/Documents/go/src/github.com/smira/aptly/s3/public.go:265 +0x6a
github.com/smira/aptly/deb.(*PublishedRepoCollection).CleanupPrefixComponentFiles(0xc820188c30, 0xc82013dbd0, 0x1, 0xc82061de60, 0x1, 0x1, 0x7fa82109dde0, 0xc820615180, 0xc8201a7280, 0x7fa82109dd48, ...)
        /Users/smira/Documents/go/src/github.com/smira/aptly/deb/publish.go:1018 +0x6a1
github.com/smira/aptly/cmd.aptlyPublishSwitch(0xc82015c5a0, 0xc820014f20, 0x3, 0x3, 0x0, 0x0)
        /Users/smira/Documents/go/src/github.com/smira/aptly/cmd/publish_switch.go:108 +0x1685
github.com/smira/commander.(*Command).Dispatch(0xc82015c5a0, 0xc820014f20, 0x3, 0x3, 0x0, 0x0)
        /Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:305 +0x647
github.com/smira/commander.(*Command).Dispatch(0xc82015c7e0, 0xc820014f10, 0x4, 0x4, 0x0, 0x0)
        /Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:283 +0x1f0
github.com/smira/commander.(*Command).Dispatch(0xc82015cfc0, 0xc820014f00, 0x5, 0x5, 0x0, 0x0)
        /Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:283 +0x1f0
github.com/smira/aptly/cmd.Run(0xc82015cfc0, 0xc82000a0b0, 0x9, 0x9, 0xd31201, 0x0)
        /Users/smira/Documents/go/src/github.com/smira/aptly/cmd/run.go:40 +0x19a
main.main()
        /Users/smira/Documents/go/src/github.com/smira/aptly/main.go:9 +0x73

goroutine 6 [syscall]:
os/signal.loop()
        /usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [runnable]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc820142380)
        /Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x29d
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        /Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x26b
```

**Comment by smira** [comment]
@david-gregory-inmar this seems to be different issue, let me prepare fix for that

**Comment by smira** [comment]
Contents generation could be disabled by default now with config option `skipContentsPublishing`

**Comment by smira** [comment]
`aptly_0.9.7~dev+17+gffafed4` nightly build includes this fix

**Comment by david-gregory-inmar** [comment]
Thanks for looking at that so quickly!  This will be a busy week, I will try to test the fix as soon as possible.

**Comment by jstangroome** [comment]
Which repo contains the `aptly_0.9.7~dev+17+gffafed4` build? I'm hitting the `panic: unable to unxz` issue too.

**Comment by smira** [comment]
With any build of aptly you can disable contents generation with `-skip-contents` flag.

**Comment by smira** [comment]
Nightly builds repo: https://github.com/smira/aptly#download
