### ISSUE TITLE
API crashes on Ubuntu 16.04 when directory permissions are incorrect

### ISSUE THREAD

**Issue by law** [smira/aptly#467]
Aptly's API daemon version 0.9.7, on Ubuntu 16.04, will crash on any HTTP request when the daemon is run as the 'aptly' user and the files under rootDir are owned by someone else ('root', in my case).  tl; dr - the aptly daemon should check file permissions beforehand and throw a user-parseable error instead of blindly crashing.  

```
$ cat /etc/aptly.conf 
{
  "rootDir": "/var/aptly",
  "architectures": ["amd64"],
      "downloadConcurrency": 4,
      "downloadSpeedLimit": 0,
      "dependencyFollowSuggests": false,
      "dependencyFollowRecommends": false,
      "dependencyFollowAllVariants": false,
      "dependencyFollowSource": false,
      "gpgDisableSign": false,
      "gpgDisableVerify": false,
      "downloadSourcePackages": false,
    "ppaDistributorID": "ubuntu",
  "ppaCodename": "",
  "S3PublishEndpoints": {}
}
```

```
# Aptly api serve starts normally
[08:43:56 aptly@repo:~] $ aptly api serve --listen 127.0.0.1:8080 -no-lock=true

Starting web server at: 127.0.0.1:8080 (press Ctrl+C to quit)...
[GIN-debug] GET   /api/version              --> github.com/smira/aptly/api.apiVersion (5 handlers)
[GIN-debug] GET   /api/repos                --> github.com/smira/aptly/api.apiReposList (5 handlers)
[GIN-debug] POST  /api/repos                --> github.com/smira/aptly/api.apiReposCreate (5 handlers)
[GIN-debug] GET   /api/repos/:name          --> github.com/smira/aptly/api.apiReposShow (5 handlers)
[GIN-debug] PUT   /api/repos/:name          --> github.com/smira/aptly/api.apiReposEdit (5 handlers)
[GIN-debug] DELETE /api/repos/:name          --> github.com/smira/aptly/api.apiReposDrop (5 handlers)
[GIN-debug] GET   /api/repos/:name/packages --> github.com/smira/aptly/api.apiReposPackagesShow (5 handlers)
[GIN-debug] POST  /api/repos/:name/packages --> github.com/smira/aptly/api.apiReposPackagesAdd (5 handlers)
[GIN-debug] DELETE /api/repos/:name/packages --> github.com/smira/aptly/api.apiReposPackagesDelete (5 handlers)
[GIN-debug] POST  /api/repos/:name/file/:dir/:file --> github.com/smira/aptly/api.apiReposPackageFromFile (5 handlers)
[GIN-debug] POST  /api/repos/:name/file/:dir --> github.com/smira/aptly/api.apiReposPackageFromDir (5 handlers)
[GIN-debug] POST  /api/repos/:name/snapshots --> github.com/smira/aptly/api.apiSnapshotsCreateFromRepository (5 handlers)
[GIN-debug] POST  /api/mirrors/:name/snapshots --> github.com/smira/aptly/api.apiSnapshotsCreateFromMirror (5 handlers)
[GIN-debug] GET   /api/files                --> github.com/smira/aptly/api.apiFilesListDirs (5 handlers)
[GIN-debug] POST  /api/files/:dir           --> github.com/smira/aptly/api.apiFilesUpload (5 handlers)
[GIN-debug] GET   /api/files/:dir           --> github.com/smira/aptly/api.apiFilesListFiles (5 handlers)
[GIN-debug] DELETE /api/files/:dir           --> github.com/smira/aptly/api.apiFilesDeleteDir (5 handlers)
[GIN-debug] DELETE /api/files/:dir/:name     --> github.com/smira/aptly/api.apiFilesDeleteFile (5 handlers)
[GIN-debug] GET   /api/publish              --> github.com/smira/aptly/api.apiPublishList (5 handlers)
[GIN-debug] POST  /api/publish              --> github.com/smira/aptly/api.apiPublishRepoOrSnapshot (5 handlers)
[GIN-debug] POST  /api/publish/:prefix      --> github.com/smira/aptly/api.apiPublishRepoOrSnapshot (5 handlers)
[GIN-debug] PUT   /api/publish/:prefix/:distribution --> github.com/smira/aptly/api.apiPublishUpdateSwitch (5 handlers)
[GIN-debug] DELETE /api/publish/:prefix/:distribution --> github.com/smira/aptly/api.apiPublishDrop (5 handlers)
[GIN-debug] GET   /api/snapshots            --> github.com/smira/aptly/api.apiSnapshotsList (5 handlers)
[GIN-debug] POST  /api/snapshots            --> github.com/smira/aptly/api.apiSnapshotsCreate (5 handlers)
[GIN-debug] PUT   /api/snapshots/:name      --> github.com/smira/aptly/api.apiSnapshotsUpdate (5 handlers)
[GIN-debug] GET   /api/snapshots/:name      --> github.com/smira/aptly/api.apiSnapshotsShow (5 handlers)
[GIN-debug] GET   /api/snapshots/:name/packages --> github.com/smira/aptly/api.apiSnapshotsSearchPackages (5 handlers)
[GIN-debug] DELETE /api/snapshots/:name      --> github.com/smira/aptly/api.apiSnapshotsDrop (5 handlers)
[GIN-debug] GET   /api/snapshots/:name/diff/:withSnapshot --> github.com/smira/aptly/api.apiSnapshotsDiff (5 handlers)
[GIN-debug] GET   /api/packages/:key        --> github.com/smira/aptly/api.apiPackagesShow (5 handlers)
[GIN-debug] GET   /api/graph.:ext           --> github.com/smira/aptly/api.apiGraph (5 handlers)
```
In another terminal, I ran 'curl localhost:8080/api/repos/', and instead of a repo-listing, got 'cmd returned a blank document'.  In the 'aptly api serve' window, this was output: 
```
panic: (*context.FatalError) (0xa37900,0xc82015f1c0)

goroutine 7 [running]:
github.com/smira/aptly/context.Fatal(0x7fdd97573028, 0xc8201699e0)
	/Users/smira/Documents/go/src/github.com/smira/aptly/context/context.go:63 +0xf1
github.com/smira/aptly/context.(*AptlyContext).CollectionFactory(0xc8200cda20, 0x0)
	/Users/smira/Documents/go/src/github.com/smira/aptly/context/context.go:288 +0xce
github.com/smira/aptly/api.flushColections()
	/Users/smira/Documents/go/src/github.com/smira/aptly/api/api.go:33 +0x27
github.com/smira/aptly/api.acquireDatabase(0xc82000a8a0, 0xc82000a900)
	/Users/smira/Documents/go/src/github.com/smira/aptly/api/api.go:93 +0x113
created by github.com/smira/aptly/api.Router
	/Users/smira/Documents/go/src/github.com/smira/aptly/api/router.go:25 +0x233



goroutine 1 [IO wait]:
net.runtime_pollWait(0x7fdd97578e00, 0x72, 0xc82000e1c0)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82018d950, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82018d950, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82018d8f0, 0x0, 0x7fdd97578ef8, 0xc82015eea0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820026398, 0x450180, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820026398, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc8201941e0, 0x7fdd97578ec0, 0xc820026398, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc8201941e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc820168750, 0xe, 0x7fdd97577e00, 0xc82009e400, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1967 +0x8f
github.com/smira/aptly/cmd.aptlyAPIServe(0xc820167320, 0xc82015e3d0, 0x0, 0x0, 0x0, 0x0)
	/Users/smira/Documents/go/src/github.com/smira/aptly/cmd/api_serve.go:25 +0x260
github.com/smira/commander.(*Command).Dispatch(0xc820167320, 0xc82015e3d0, 0x0, 0x0, 0x0, 0x0)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:305 +0x647
github.com/smira/commander.(*Command).Dispatch(0xc820167440, 0xc82015e3d0, 0x1, 0x1, 0x0, 0x0)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:283 +0x1f0
github.com/smira/commander.(*Command).Dispatch(0xc820167560, 0xc82015e3c0, 0x2, 0x2, 0x0, 0x0)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:283 +0x1f0
github.com/smira/aptly/cmd.Run(0xc820167560, 0xc82000a190, 0x5, 0x5, 0xd3ed01, 0x0)
	/Users/smira/Documents/go/src/github.com/smira/aptly/cmd/run.go:40 +0x19a
main.main()
	/Users/smira/Documents/go/src/github.com/smira/aptly/main.go:9 +0x73

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [chan receive]:
github.com/smira/aptly/api.cacheFlusher(0xc82000a8a0, 0xc82000a900)
	/Users/smira/Documents/go/src/github.com/smira/aptly/api/api.go:62 +0x53
created by github.com/smira/aptly/api.Router
	/Users/smira/Documents/go/src/github.com/smira/aptly/api/router.go:26 +0x25f

goroutine 10 [chan receive]:
github.com/smira/aptly/api.Router.func1.1(0xc82000a8a0, 0xc8200f96e0, 0xc82000a900, 0xc820198000)
	/Users/smira/Documents/go/src/github.com/smira/aptly/api/router.go:37 +0x74
github.com/smira/aptly/context.Fatal(0x7fdd97573028, 0xc820169970)
	/Users/smira/Documents/go/src/github.com/smira/aptly/context/context.go:63 +0xf1
github.com/smira/aptly/context.(*AptlyContext).CollectionFactory(0xc8200cda20, 0x0)
	/Users/smira/Documents/go/src/github.com/smira/aptly/context/context.go:288 +0xce
github.com/smira/aptly/api.apiReposList(0xc820198000)
	/Users/smira/Documents/go/src/github.com/smira/aptly/api/repos.go:18 +0x5d
github.com/gin-gonic/gin.(*Context).Next(0xc820198000)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/gin-gonic/gin/context.go:114 +0x8f
github.com/smira/aptly/api.Router.func1(0xc820198000)
	/Users/smira/Documents/go/src/github.com/smira/aptly/api/router.go:43 +0x124
github.com/gin-gonic/gin.(*Context).Next(0xc820198000)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/gin-gonic/gin/context.go:114 +0x8f
github.com/gin-gonic/gin.ErrorLoggerT.func1(0xc820198000)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/gin-gonic/gin/logger.go:30 +0x2c
github.com/gin-gonic/gin.(*Context).Next(0xc820198000)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/gin-gonic/gin/context.go:114 +0x8f
github.com/gin-gonic/gin.Logger.func1(0xc820198000)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/gin-gonic/gin/logger.go:49 +0x65
github.com/gin-gonic/gin.(*Context).Next(0xc820198000)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/gin-gonic/gin/context.go:114 +0x8f
github.com/gin-gonic/gin.Recovery.func1(0xc820198000)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/gin-gonic/gin/recovery.go:96 +0x48
github.com/gin-gonic/gin.(*Context).Next(0xc820198000)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/gin-gonic/gin/context.go:114 +0x8f
github.com/gin-gonic/gin.(*RouterGroup).Handle.func1(0x7fdd975790a0, 0xc8200cdd90, 0xc820144380, 0x0, 0x0, 0x0)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/gin-gonic/gin/routergroup.go:57 +0xb0
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc82015e460, 0x7fdd975790a0, 0xc8200cdd90, 0xc820144380)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/julienschmidt/httprouter/router.go:276 +0x18d
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc82009e400, 0x7fdd975790a0, 0xc8200cdd90, 0xc820144380)
	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/gin-gonic/gin/gin.go:126 +0x43
net/http.serverHandler.ServeHTTP(0xc8201941e0, 0x7fdd975790a0, 0xc8200cdd90, 0xc820144380)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200cdad0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1910 +0x3f6
```

Further examination revealed the root cause to be root-owned directories under /var/aptly/.  Changing these to be owned by the 'aptly' user fixed the problem.  Perhaps the aptly daemon should check file-permissions on start and throw a human-readable error, rather than messily crash.

**Comment by smira** [comment]
Error message doesn't look good, I'll take a look.

**Comment by jola5** [comment]
Seems like an easy fix. I'll provide a PR if you're not already done @smira.
